language: python

python:
    - 2.7

notifications:
  email: false

sudo: required

install:
    - pip install --upgrade pip
    - pip install nltk
    - python -m nltk.downloader all
    - pip install pandas
    - pip install numpy
    - pip install git+http://github.com/scipy/scipy/
    - pip install -U scikit-learn

script:
    - python preprocess_csv/preprocessData.py -c speaking preprocess_csv/sample_in.csv -o sample-out.csv
    - python subset/SubsetData.py -c speaker_party -s 10 --selected-cols "speaker_party;speaking" --no-report -o sample_out.csv subset/sample_in.csv

