language: python

python:
    - 2.7

notifications:
  email: false

sudo: required

install:
    - pip install --upgrade pip
    - pip install nltk
    - python2.7 -c "import nltk; nltk.download('stopwords'); nltk.download('word_tokenize'); nltk.download('PorterStemmer')"
script:
    - python preprocess_csv/preprocessData.py -c speaking preprocess_csv/sample_in.csv -o sample-out.csv

