language: python

python:
    - 2.7

notifications:
  email: false

sudo: required

install:
    - pip install --upgrade pip
    - pip install nltk

script:
    - python preprocess_csv/preprocessData.py -c speaking preprocess_csv/sample_in.csv -o sample-out.csv

